// Code generated by protoc-gen-go. DO NOT EDIT.
// source: popcount.proto

package Spotify

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type PopcountRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *PopcountRequest) Reset()                    { *m = PopcountRequest{} }
func (m *PopcountRequest) String() string            { return proto.CompactTextString(m) }
func (*PopcountRequest) ProtoMessage()               {}
func (*PopcountRequest) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{0} }

type PopcountResult struct {
	Count                  *int64   `protobuf:"zigzag64,1,opt,name=count" json:"count,omitempty"`
	Truncated              *bool    `protobuf:"varint,2,opt,name=truncated" json:"truncated,omitempty"`
	User                   []string `protobuf:"bytes,3,rep,name=user" json:"user,omitempty"`
	SubscriptionTimestamps []int64  `protobuf:"zigzag64,4,rep,name=subscriptionTimestamps" json:"subscriptionTimestamps,omitempty"`
	InsertionTimestamps    []int64  `protobuf:"zigzag64,5,rep,name=insertionTimestamps" json:"insertionTimestamps,omitempty"`
	XXX_unrecognized       []byte   `json:"-"`
}

func (m *PopcountResult) Reset()                    { *m = PopcountResult{} }
func (m *PopcountResult) String() string            { return proto.CompactTextString(m) }
func (*PopcountResult) ProtoMessage()               {}
func (*PopcountResult) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{1} }

func (m *PopcountResult) GetCount() int64 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *PopcountResult) GetTruncated() bool {
	if m != nil && m.Truncated != nil {
		return *m.Truncated
	}
	return false
}

func (m *PopcountResult) GetUser() []string {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *PopcountResult) GetSubscriptionTimestamps() []int64 {
	if m != nil {
		return m.SubscriptionTimestamps
	}
	return nil
}

func (m *PopcountResult) GetInsertionTimestamps() []int64 {
	if m != nil {
		return m.InsertionTimestamps
	}
	return nil
}

func init() {
	proto.RegisterType((*PopcountRequest)(nil), "Spotify.PopcountRequest")
	proto.RegisterType((*PopcountResult)(nil), "Spotify.PopcountResult")
}

func init() { proto.RegisterFile("popcount.proto", fileDescriptor13) }

var fileDescriptor13 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8b, 0x41, 0xaa, 0xc2, 0x30,
	0x14, 0x45, 0xc9, 0x6f, 0xcb, 0xff, 0x7d, 0x83, 0x7e, 0x7c, 0x8a, 0x64, 0xe0, 0x20, 0x74, 0x94,
	0x91, 0x38, 0x72, 0x1d, 0x12, 0xdd, 0x40, 0xad, 0x11, 0x02, 0x36, 0x89, 0x79, 0x2f, 0x03, 0xb7,
	0xe7, 0xca, 0x84, 0x2a, 0x14, 0x44, 0x67, 0xf7, 0x9e, 0xc3, 0x81, 0x26, 0x86, 0xd8, 0x87, 0xec,
	0x79, 0x1d, 0x53, 0xe0, 0x80, 0xbf, 0xfb, 0x18, 0xd8, 0x9d, 0x6f, 0xed, 0x0c, 0xfe, 0x77, 0x2f,
	0x65, 0xec, 0x35, 0x5b, 0xe2, 0xf6, 0x2e, 0xa0, 0x99, 0x18, 0xe5, 0x0b, 0xe3, 0x02, 0xaa, 0xf1,
	0x4a, 0xa1, 0x84, 0x46, 0xf3, 0x3c, 0xb8, 0x82, 0x9a, 0x53, 0xf6, 0x7d, 0xc7, 0xf6, 0x24, 0x7f,
	0x94, 0xd0, 0x7f, 0x66, 0x02, 0x88, 0x50, 0x66, 0xb2, 0x49, 0x16, 0xaa, 0xd0, 0xb5, 0x19, 0x37,
	0x6e, 0x61, 0x49, 0xf9, 0x48, 0x7d, 0x72, 0x91, 0x5d, 0xf0, 0x07, 0x37, 0x58, 0xe2, 0x6e, 0x88,
	0x24, 0x4b, 0x55, 0x68, 0x34, 0x5f, 0x2c, 0x6e, 0x60, 0xee, 0x3c, 0xd9, 0xf4, 0x16, 0x55, 0x63,
	0xf4, 0x49, 0x3d, 0x02, 0x00, 0x00, 0xff, 0xff, 0x86, 0x34, 0x8e, 0x49, 0xf1, 0x00, 0x00, 0x00,
}
