// Code generated by protoc-gen-go.
// source: facebook-publish.proto
// DO NOT EDIT!

package Spotify

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type EventReply struct {
	Queued           *int32     `protobuf:"varint,1,opt,name=queued" json:"queued,omitempty"`
	Retry            *RetryInfo `protobuf:"bytes,2,opt,name=retry" json:"retry,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *EventReply) Reset()                    { *m = EventReply{} }
func (m *EventReply) String() string            { return proto.CompactTextString(m) }
func (*EventReply) ProtoMessage()               {}
func (*EventReply) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *EventReply) GetQueued() int32 {
	if m != nil && m.Queued != nil {
		return *m.Queued
	}
	return 0
}

func (m *EventReply) GetRetry() *RetryInfo {
	if m != nil {
		return m.Retry
	}
	return nil
}

type RetryInfo struct {
	RetryDelay       *int32 `protobuf:"varint,1,opt,name=retry_delay" json:"retry_delay,omitempty"`
	MaxRetry         *int32 `protobuf:"varint,2,opt,name=max_retry" json:"max_retry,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RetryInfo) Reset()                    { *m = RetryInfo{} }
func (m *RetryInfo) String() string            { return proto.CompactTextString(m) }
func (*RetryInfo) ProtoMessage()               {}
func (*RetryInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *RetryInfo) GetRetryDelay() int32 {
	if m != nil && m.RetryDelay != nil {
		return *m.RetryDelay
	}
	return 0
}

func (m *RetryInfo) GetMaxRetry() int32 {
	if m != nil && m.MaxRetry != nil {
		return *m.MaxRetry
	}
	return 0
}

type Id struct {
	Uri              *string `protobuf:"bytes,1,opt,name=uri" json:"uri,omitempty"`
	StartTime        *int64  `protobuf:"varint,2,opt,name=start_time" json:"start_time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Id) Reset()                    { *m = Id{} }
func (m *Id) String() string            { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()               {}
func (*Id) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *Id) GetUri() string {
	if m != nil && m.Uri != nil {
		return *m.Uri
	}
	return ""
}

func (m *Id) GetStartTime() int64 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

type Start struct {
	Length           *int32  `protobuf:"varint,1,opt,name=length" json:"length,omitempty"`
	ContextUri       *string `protobuf:"bytes,2,opt,name=context_uri" json:"context_uri,omitempty"`
	EndTime          *int64  `protobuf:"varint,3,opt,name=end_time" json:"end_time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Start) Reset()                    { *m = Start{} }
func (m *Start) String() string            { return proto.CompactTextString(m) }
func (*Start) ProtoMessage()               {}
func (*Start) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *Start) GetLength() int32 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *Start) GetContextUri() string {
	if m != nil && m.ContextUri != nil {
		return *m.ContextUri
	}
	return ""
}

func (m *Start) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

type Seek struct {
	EndTime          *int64 `protobuf:"varint,1,opt,name=end_time" json:"end_time,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Seek) Reset()                    { *m = Seek{} }
func (m *Seek) String() string            { return proto.CompactTextString(m) }
func (*Seek) ProtoMessage()               {}
func (*Seek) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *Seek) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

type Pause struct {
	SecondsPlayed    *int32 `protobuf:"varint,1,opt,name=seconds_played" json:"seconds_played,omitempty"`
	EndTime          *int64 `protobuf:"varint,2,opt,name=end_time" json:"end_time,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Pause) Reset()                    { *m = Pause{} }
func (m *Pause) String() string            { return proto.CompactTextString(m) }
func (*Pause) ProtoMessage()               {}
func (*Pause) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *Pause) GetSecondsPlayed() int32 {
	if m != nil && m.SecondsPlayed != nil {
		return *m.SecondsPlayed
	}
	return 0
}

func (m *Pause) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

type Resume struct {
	SecondsPlayed    *int32 `protobuf:"varint,1,opt,name=seconds_played" json:"seconds_played,omitempty"`
	EndTime          *int64 `protobuf:"varint,2,opt,name=end_time" json:"end_time,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Resume) Reset()                    { *m = Resume{} }
func (m *Resume) String() string            { return proto.CompactTextString(m) }
func (*Resume) ProtoMessage()               {}
func (*Resume) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *Resume) GetSecondsPlayed() int32 {
	if m != nil && m.SecondsPlayed != nil {
		return *m.SecondsPlayed
	}
	return 0
}

func (m *Resume) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

type End struct {
	SecondsPlayed    *int32 `protobuf:"varint,1,opt,name=seconds_played" json:"seconds_played,omitempty"`
	EndTime          *int64 `protobuf:"varint,2,opt,name=end_time" json:"end_time,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *End) Reset()                    { *m = End{} }
func (m *End) String() string            { return proto.CompactTextString(m) }
func (*End) ProtoMessage()               {}
func (*End) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *End) GetSecondsPlayed() int32 {
	if m != nil && m.SecondsPlayed != nil {
		return *m.SecondsPlayed
	}
	return 0
}

func (m *End) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

type Event struct {
	Id               *Id     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Start            *Start  `protobuf:"bytes,2,opt,name=start" json:"start,omitempty"`
	Seek             *Seek   `protobuf:"bytes,3,opt,name=seek" json:"seek,omitempty"`
	Pause            *Pause  `protobuf:"bytes,4,opt,name=pause" json:"pause,omitempty"`
	Resume           *Resume `protobuf:"bytes,5,opt,name=resume" json:"resume,omitempty"`
	End              *End    `protobuf:"bytes,6,opt,name=end" json:"end,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *Event) GetId() *Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Event) GetStart() *Start {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *Event) GetSeek() *Seek {
	if m != nil {
		return m.Seek
	}
	return nil
}

func (m *Event) GetPause() *Pause {
	if m != nil {
		return m.Pause
	}
	return nil
}

func (m *Event) GetResume() *Resume {
	if m != nil {
		return m.Resume
	}
	return nil
}

func (m *Event) GetEnd() *End {
	if m != nil {
		return m.End
	}
	return nil
}

func init() {
	proto.RegisterType((*EventReply)(nil), "Spotify.EventReply")
	proto.RegisterType((*RetryInfo)(nil), "Spotify.RetryInfo")
	proto.RegisterType((*Id)(nil), "Spotify.Id")
	proto.RegisterType((*Start)(nil), "Spotify.Start")
	proto.RegisterType((*Seek)(nil), "Spotify.Seek")
	proto.RegisterType((*Pause)(nil), "Spotify.Pause")
	proto.RegisterType((*Resume)(nil), "Spotify.Resume")
	proto.RegisterType((*End)(nil), "Spotify.End")
	proto.RegisterType((*Event)(nil), "Spotify.Event")
}

var fileDescriptor1 = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x51, 0x41, 0x4f, 0xb3, 0x40,
	0x10, 0x0d, 0xd0, 0xe5, 0xfb, 0x3a, 0x68, 0xd5, 0x35, 0xa9, 0x18, 0x63, 0x54, 0x12, 0x13, 0x2f,
	0xd6, 0x88, 0x77, 0x3d, 0xf5, 0xd0, 0x9b, 0x69, 0x7f, 0x00, 0xa1, 0x65, 0x6a, 0x49, 0x29, 0x8b,
	0xec, 0x62, 0xca, 0x2f, 0xf3, 0xef, 0xb9, 0x3b, 0x10, 0x5a, 0xbd, 0xf5, 0xb8, 0xf3, 0xe6, 0xbd,
	0x7d, 0xef, 0x0d, 0x0c, 0x97, 0xf1, 0x02, 0xe7, 0x42, 0xac, 0x1f, 0x8b, 0x6a, 0x9e, 0xa5, 0x72,
	0x35, 0x2a, 0x4a, 0xa1, 0x04, 0xff, 0x37, 0x2b, 0x84, 0x4a, 0x97, 0x75, 0xf0, 0x06, 0x30, 0xfe,
	0xc2, 0x5c, 0x4d, 0xb1, 0xc8, 0x6a, 0x3e, 0x00, 0xf7, 0xb3, 0xc2, 0x0a, 0x13, 0xdf, 0xba, 0xb5,
	0x1e, 0x18, 0xbf, 0x03, 0x56, 0xa2, 0x2a, 0x6b, 0xdf, 0xd6, 0x4f, 0x2f, 0xe4, 0xa3, 0x96, 0x36,
	0x9a, 0x9a, 0xe9, 0x24, 0x5f, 0x8a, 0xe0, 0x05, 0xfa, 0xdd, 0x83, 0x9f, 0x83, 0x47, 0xfb, 0x51,
	0x82, 0x59, 0x5c, 0xb7, 0x22, 0x67, 0xd0, 0xdf, 0xc4, 0xdb, 0x68, 0x27, 0xc4, 0x82, 0x7b, 0xb0,
	0x27, 0x09, 0xf7, 0xc0, 0xa9, 0xca, 0x94, 0xb6, 0xfa, 0x9c, 0x03, 0x48, 0x15, 0x97, 0x2a, 0x52,
	0xe9, 0x06, 0x69, 0xcd, 0x09, 0x5e, 0x81, 0xcd, 0xcc, 0xcc, 0xf8, 0xca, 0x30, 0xff, 0x50, 0xab,
	0x56, 0x52, 0xff, 0xb3, 0x10, 0xb9, 0xc2, 0xad, 0x8a, 0x8c, 0x82, 0x4d, 0x0a, 0xa7, 0xf0, 0x1f,
	0xf3, 0xa4, 0xe1, 0x3b, 0xc4, 0xf7, 0xa1, 0x37, 0x43, 0x5c, 0xff, 0x42, 0x2c, 0x42, 0x9e, 0x81,
	0xbd, 0xc7, 0x95, 0x44, 0x3e, 0x84, 0x81, 0x44, 0xad, 0x95, 0xc8, 0xa8, 0xd0, 0x96, 0xbb, 0xe4,
	0xfb, 0x94, 0xc6, 0x4c, 0x08, 0xee, 0x14, 0x65, 0xb5, 0x39, 0x84, 0xf3, 0x04, 0xce, 0x38, 0x4f,
	0x0e, 0x20, 0x7c, 0x5b, 0xc0, 0xe8, 0x1e, 0xfc, 0x02, 0xec, 0xb4, 0xd9, 0xf3, 0x42, 0xaf, 0xeb,
	0x5d, 0xb7, 0x76, 0x0d, 0x8c, 0x8a, 0x6a, 0x6f, 0x32, 0xe8, 0xb0, 0xa6, 0xaa, 0x2b, 0xe8, 0x49,
	0x9d, 0x99, 0x1a, 0xf0, 0xc2, 0xe3, 0x1d, 0x6a, 0x8a, 0xd0, 0xdc, 0xc2, 0xc4, 0xf6, 0x7b, 0x7f,
	0xb8, 0x4d, 0x19, 0x37, 0xe0, 0x96, 0x14, 0xd1, 0x67, 0x84, 0x9f, 0xec, 0xdd, 0x9b, 0x92, 0x5f,
	0x82, 0xa3, 0x0d, 0xfb, 0x2e, 0xa1, 0x47, 0x1d, 0xaa, 0x33, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff,
	0xbe, 0xf2, 0x5a, 0x09, 0x6a, 0x02, 0x00, 0x00,
}
