// Code generated by protoc-gen-go.
// source: facebook-publish.proto
// DO NOT EDIT!

package Spotify

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type EventReply struct {
	Queued           *int32     `protobuf:"varint,1,opt,name=queued" json:"queued,omitempty"`
	Retry            *RetryInfo `protobuf:"bytes,2,opt,name=retry" json:"retry,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *EventReply) Reset()                    { *m = EventReply{} }
func (m *EventReply) String() string            { return proto.CompactTextString(m) }
func (*EventReply) ProtoMessage()               {}
func (*EventReply) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *EventReply) GetQueued() int32 {
	if m != nil && m.Queued != nil {
		return *m.Queued
	}
	return 0
}

func (m *EventReply) GetRetry() *RetryInfo {
	if m != nil {
		return m.Retry
	}
	return nil
}

type RetryInfo struct {
	RetryDelay       *int32 `protobuf:"varint,1,opt,name=retry_delay,json=retryDelay" json:"retry_delay,omitempty"`
	MaxRetry         *int32 `protobuf:"varint,2,opt,name=max_retry,json=maxRetry" json:"max_retry,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RetryInfo) Reset()                    { *m = RetryInfo{} }
func (m *RetryInfo) String() string            { return proto.CompactTextString(m) }
func (*RetryInfo) ProtoMessage()               {}
func (*RetryInfo) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *RetryInfo) GetRetryDelay() int32 {
	if m != nil && m.RetryDelay != nil {
		return *m.RetryDelay
	}
	return 0
}

func (m *RetryInfo) GetMaxRetry() int32 {
	if m != nil && m.MaxRetry != nil {
		return *m.MaxRetry
	}
	return 0
}

type Id struct {
	Uri              *string `protobuf:"bytes,1,opt,name=uri" json:"uri,omitempty"`
	StartTime        *int64  `protobuf:"varint,2,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Id) Reset()                    { *m = Id{} }
func (m *Id) String() string            { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()               {}
func (*Id) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *Id) GetUri() string {
	if m != nil && m.Uri != nil {
		return *m.Uri
	}
	return ""
}

func (m *Id) GetStartTime() int64 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

type Start struct {
	Length           *int32  `protobuf:"varint,1,opt,name=length" json:"length,omitempty"`
	ContextUri       *string `protobuf:"bytes,2,opt,name=context_uri,json=contextUri" json:"context_uri,omitempty"`
	EndTime          *int64  `protobuf:"varint,3,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Start) Reset()                    { *m = Start{} }
func (m *Start) String() string            { return proto.CompactTextString(m) }
func (*Start) ProtoMessage()               {}
func (*Start) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *Start) GetLength() int32 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *Start) GetContextUri() string {
	if m != nil && m.ContextUri != nil {
		return *m.ContextUri
	}
	return ""
}

func (m *Start) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

type Seek struct {
	EndTime          *int64 `protobuf:"varint,1,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Seek) Reset()                    { *m = Seek{} }
func (m *Seek) String() string            { return proto.CompactTextString(m) }
func (*Seek) ProtoMessage()               {}
func (*Seek) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

func (m *Seek) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

type Pause struct {
	SecondsPlayed    *int32 `protobuf:"varint,1,opt,name=seconds_played,json=secondsPlayed" json:"seconds_played,omitempty"`
	EndTime          *int64 `protobuf:"varint,2,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Pause) Reset()                    { *m = Pause{} }
func (m *Pause) String() string            { return proto.CompactTextString(m) }
func (*Pause) ProtoMessage()               {}
func (*Pause) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{5} }

func (m *Pause) GetSecondsPlayed() int32 {
	if m != nil && m.SecondsPlayed != nil {
		return *m.SecondsPlayed
	}
	return 0
}

func (m *Pause) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

type Resume struct {
	SecondsPlayed    *int32 `protobuf:"varint,1,opt,name=seconds_played,json=secondsPlayed" json:"seconds_played,omitempty"`
	EndTime          *int64 `protobuf:"varint,2,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Resume) Reset()                    { *m = Resume{} }
func (m *Resume) String() string            { return proto.CompactTextString(m) }
func (*Resume) ProtoMessage()               {}
func (*Resume) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{6} }

func (m *Resume) GetSecondsPlayed() int32 {
	if m != nil && m.SecondsPlayed != nil {
		return *m.SecondsPlayed
	}
	return 0
}

func (m *Resume) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

type End struct {
	SecondsPlayed    *int32 `protobuf:"varint,1,opt,name=seconds_played,json=secondsPlayed" json:"seconds_played,omitempty"`
	EndTime          *int64 `protobuf:"varint,2,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *End) Reset()                    { *m = End{} }
func (m *End) String() string            { return proto.CompactTextString(m) }
func (*End) ProtoMessage()               {}
func (*End) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{7} }

func (m *End) GetSecondsPlayed() int32 {
	if m != nil && m.SecondsPlayed != nil {
		return *m.SecondsPlayed
	}
	return 0
}

func (m *End) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

type Event struct {
	Id               *Id     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Start            *Start  `protobuf:"bytes,2,opt,name=start" json:"start,omitempty"`
	Seek             *Seek   `protobuf:"bytes,3,opt,name=seek" json:"seek,omitempty"`
	Pause            *Pause  `protobuf:"bytes,4,opt,name=pause" json:"pause,omitempty"`
	Resume           *Resume `protobuf:"bytes,5,opt,name=resume" json:"resume,omitempty"`
	End              *End    `protobuf:"bytes,6,opt,name=end" json:"end,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{8} }

func (m *Event) GetId() *Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Event) GetStart() *Start {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *Event) GetSeek() *Seek {
	if m != nil {
		return m.Seek
	}
	return nil
}

func (m *Event) GetPause() *Pause {
	if m != nil {
		return m.Pause
	}
	return nil
}

func (m *Event) GetResume() *Resume {
	if m != nil {
		return m.Resume
	}
	return nil
}

func (m *Event) GetEnd() *End {
	if m != nil {
		return m.End
	}
	return nil
}

func init() {
	proto.RegisterType((*EventReply)(nil), "Spotify.EventReply")
	proto.RegisterType((*RetryInfo)(nil), "Spotify.RetryInfo")
	proto.RegisterType((*Id)(nil), "Spotify.Id")
	proto.RegisterType((*Start)(nil), "Spotify.Start")
	proto.RegisterType((*Seek)(nil), "Spotify.Seek")
	proto.RegisterType((*Pause)(nil), "Spotify.Pause")
	proto.RegisterType((*Resume)(nil), "Spotify.Resume")
	proto.RegisterType((*End)(nil), "Spotify.End")
	proto.RegisterType((*Event)(nil), "Spotify.Event")
}

func init() { proto.RegisterFile("facebook-publish.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 405 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x92, 0xcf, 0xae, 0x9a, 0x40,
	0x14, 0x87, 0x03, 0x38, 0x28, 0x87, 0x6a, 0x9b, 0x59, 0x18, 0x9a, 0xa6, 0xff, 0x48, 0x9b, 0xba,
	0xa9, 0x0b, 0x93, 0xbe, 0x41, 0x4d, 0x43, 0x17, 0x8d, 0x19, 0xdb, 0x55, 0x17, 0x04, 0xe5, 0x58,
	0x89, 0x08, 0x14, 0x86, 0x1b, 0x79, 0xd7, 0xfb, 0x30, 0x77, 0xe6, 0xc0, 0xc5, 0xcb, 0x5d, 0xbb,
	0x73, 0xbe, 0x73, 0xe6, 0x93, 0xf3, 0x9b, 0x03, 0xf3, 0x43, 0xb4, 0xc7, 0x5d, 0x9e, 0x9f, 0xbe,
	0x16, 0xf5, 0x2e, 0x4d, 0xaa, 0xe3, 0xb2, 0x28, 0x73, 0x99, 0xf3, 0xf1, 0xb6, 0xc8, 0x65, 0x72,
	0x68, 0xfc, 0x5f, 0x00, 0xeb, 0x3b, 0xcc, 0xa4, 0xc0, 0x22, 0x6d, 0xf8, 0x1c, 0xec, 0xff, 0x35,
	0xd6, 0x18, 0x7b, 0xc6, 0x07, 0x63, 0xc1, 0x44, 0x77, 0xe2, 0x0b, 0x60, 0x25, 0xca, 0xb2, 0xf1,
	0x4c, 0x85, 0xdd, 0x15, 0x5f, 0x76, 0xd7, 0x97, 0x42, 0xd3, 0x20, 0x3b, 0xe4, 0xa2, 0x6d, 0xf0,
	0x03, 0x70, 0x7a, 0xc6, 0xdf, 0x83, 0x4b, 0x34, 0x8c, 0x31, 0x8d, 0x9a, 0xce, 0x09, 0x84, 0xbe,
	0x6b, 0xc2, 0xdf, 0x80, 0x73, 0x8e, 0x2e, 0xe1, 0xd5, 0xcd, 0xc4, 0x44, 0x01, 0x32, 0xf8, 0xdf,
	0xc0, 0x0c, 0x62, 0xfe, 0x0a, 0xac, 0xba, 0x4c, 0xe8, 0xae, 0x23, 0xf4, 0x4f, 0xfe, 0x16, 0xa0,
	0x92, 0x51, 0x29, 0x43, 0x99, 0x9c, 0x91, 0x6e, 0x59, 0xc2, 0x21, 0xf2, 0x5b, 0x01, 0xff, 0x2f,
	0xb0, 0xad, 0x3e, 0xe8, 0x61, 0x52, 0xcc, 0xfe, 0xc9, 0xe3, 0xe3, 0x30, 0xed, 0x49, 0x7f, 0xd5,
	0x3e, 0xcf, 0x24, 0x5e, 0x64, 0xa8, 0xcd, 0x26, 0x99, 0xa1, 0x43, 0x7f, 0xd4, 0x1f, 0xbc, 0x86,
	0x09, 0x66, 0x71, 0xab, 0xb7, 0x48, 0x3f, 0x56, 0x67, 0x92, 0x7f, 0x84, 0xd1, 0x16, 0xf1, 0x34,
	0x68, 0x31, 0x86, 0x2d, 0x01, 0xb0, 0x4d, 0x54, 0x57, 0xc8, 0x3f, 0xc3, 0xac, 0x42, 0xa5, 0x8d,
	0xab, 0xb0, 0x50, 0xc3, 0xf6, 0xa1, 0x4e, 0x3b, 0xba, 0x21, 0x38, 0x50, 0x99, 0x43, 0xd5, 0x4f,
	0xb0, 0x05, 0x56, 0xf5, 0xf9, 0x16, 0xae, 0x1f, 0x60, 0xad, 0xb3, 0xf8, 0x06, 0xa2, 0x7b, 0x03,
	0x18, 0xad, 0x8c, 0x7a, 0x3d, 0x33, 0x69, 0xef, 0xbb, 0x2b, 0xb7, 0x5f, 0x89, 0x20, 0x16, 0x0a,
	0xf3, 0x4f, 0xc0, 0xe8, 0x4d, 0xba, 0x95, 0x99, 0xf5, 0x75, 0x7a, 0x1c, 0xd1, 0x16, 0xb9, 0xca,
	0xb3, 0x52, 0x79, 0x52, 0xcc, 0xee, 0x6a, 0x7a, 0x6d, 0x52, 0x50, 0x50, 0x49, 0x8b, 0x0a, 0x9d,
	0xa7, 0x37, 0x7a, 0x26, 0xa2, 0x94, 0x45, 0x5b, 0xe4, 0x5f, 0xc0, 0x2e, 0x29, 0x2a, 0x8f, 0x51,
	0xdb, 0xcb, 0x27, 0x2b, 0xaa, 0xb1, 0xe8, 0xca, 0xfc, 0x1d, 0x58, 0x6a, 0x12, 0xcf, 0xa6, 0xae,
	0x17, 0x7d, 0x97, 0xca, 0x46, 0xe8, 0xc2, 0x43, 0x00, 0x00, 0x00, 0xff, 0xff, 0x66, 0xd3, 0xcb,
	0x6e, 0x32, 0x03, 0x00, 0x00,
}
