// Code generated by protoc-gen-go.
// source: playlist4content.proto
// DO NOT EDIT!

package Spotify

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Item struct {
	Uri              *string         `protobuf:"bytes,1,opt,name=uri" json:"uri,omitempty"`
	Attributes       *ItemAttributes `protobuf:"bytes,2,opt,name=attributes" json:"attributes,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Item) Reset()                    { *m = Item{} }
func (m *Item) String() string            { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()               {}
func (*Item) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{0} }

func (m *Item) GetUri() string {
	if m != nil && m.Uri != nil {
		return *m.Uri
	}
	return ""
}

func (m *Item) GetAttributes() *ItemAttributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type ListItems struct {
	Pos              *int32  `protobuf:"varint,1,opt,name=pos" json:"pos,omitempty"`
	Truncated        *bool   `protobuf:"varint,2,opt,name=truncated" json:"truncated,omitempty"`
	Items            []*Item `protobuf:"bytes,3,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ListItems) Reset()                    { *m = ListItems{} }
func (m *ListItems) String() string            { return proto.CompactTextString(m) }
func (*ListItems) ProtoMessage()               {}
func (*ListItems) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{1} }

func (m *ListItems) GetPos() int32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

func (m *ListItems) GetTruncated() bool {
	if m != nil && m.Truncated != nil {
		return *m.Truncated
	}
	return false
}

func (m *ListItems) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type ContentRange struct {
	Pos              *int32 `protobuf:"varint,1,opt,name=pos" json:"pos,omitempty"`
	Length           *int32 `protobuf:"varint,2,opt,name=length" json:"length,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ContentRange) Reset()                    { *m = ContentRange{} }
func (m *ContentRange) String() string            { return proto.CompactTextString(m) }
func (*ContentRange) ProtoMessage()               {}
func (*ContentRange) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{2} }

func (m *ContentRange) GetPos() int32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

func (m *ContentRange) GetLength() int32 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

type ListContentSelection struct {
	WantRevision          *bool                  `protobuf:"varint,1,opt,name=wantRevision" json:"wantRevision,omitempty"`
	WantLength            *bool                  `protobuf:"varint,2,opt,name=wantLength" json:"wantLength,omitempty"`
	WantAttributes        *bool                  `protobuf:"varint,3,opt,name=wantAttributes" json:"wantAttributes,omitempty"`
	WantChecksum          *bool                  `protobuf:"varint,4,opt,name=wantChecksum" json:"wantChecksum,omitempty"`
	WantContent           *bool                  `protobuf:"varint,5,opt,name=wantContent" json:"wantContent,omitempty"`
	ContentRange          *ContentRange          `protobuf:"bytes,6,opt,name=contentRange" json:"contentRange,omitempty"`
	WantDiff              *bool                  `protobuf:"varint,7,opt,name=wantDiff" json:"wantDiff,omitempty"`
	BaseRevision          []byte                 `protobuf:"bytes,8,opt,name=baseRevision" json:"baseRevision,omitempty"`
	HintRevision          []byte                 `protobuf:"bytes,9,opt,name=hintRevision" json:"hintRevision,omitempty"`
	WantNothingIfUpToDate *bool                  `protobuf:"varint,10,opt,name=wantNothingIfUpToDate" json:"wantNothingIfUpToDate,omitempty"`
	WantResolveAction     *bool                  `protobuf:"varint,12,opt,name=wantResolveAction" json:"wantResolveAction,omitempty"`
	Issues                []*ClientIssue         `protobuf:"bytes,13,rep,name=issues" json:"issues,omitempty"`
	ResolveAction         []*ClientResolveAction `protobuf:"bytes,14,rep,name=resolveAction" json:"resolveAction,omitempty"`
	XXX_unrecognized      []byte                 `json:"-"`
}

func (m *ListContentSelection) Reset()                    { *m = ListContentSelection{} }
func (m *ListContentSelection) String() string            { return proto.CompactTextString(m) }
func (*ListContentSelection) ProtoMessage()               {}
func (*ListContentSelection) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{3} }

func (m *ListContentSelection) GetWantRevision() bool {
	if m != nil && m.WantRevision != nil {
		return *m.WantRevision
	}
	return false
}

func (m *ListContentSelection) GetWantLength() bool {
	if m != nil && m.WantLength != nil {
		return *m.WantLength
	}
	return false
}

func (m *ListContentSelection) GetWantAttributes() bool {
	if m != nil && m.WantAttributes != nil {
		return *m.WantAttributes
	}
	return false
}

func (m *ListContentSelection) GetWantChecksum() bool {
	if m != nil && m.WantChecksum != nil {
		return *m.WantChecksum
	}
	return false
}

func (m *ListContentSelection) GetWantContent() bool {
	if m != nil && m.WantContent != nil {
		return *m.WantContent
	}
	return false
}

func (m *ListContentSelection) GetContentRange() *ContentRange {
	if m != nil {
		return m.ContentRange
	}
	return nil
}

func (m *ListContentSelection) GetWantDiff() bool {
	if m != nil && m.WantDiff != nil {
		return *m.WantDiff
	}
	return false
}

func (m *ListContentSelection) GetBaseRevision() []byte {
	if m != nil {
		return m.BaseRevision
	}
	return nil
}

func (m *ListContentSelection) GetHintRevision() []byte {
	if m != nil {
		return m.HintRevision
	}
	return nil
}

func (m *ListContentSelection) GetWantNothingIfUpToDate() bool {
	if m != nil && m.WantNothingIfUpToDate != nil {
		return *m.WantNothingIfUpToDate
	}
	return false
}

func (m *ListContentSelection) GetWantResolveAction() bool {
	if m != nil && m.WantResolveAction != nil {
		return *m.WantResolveAction
	}
	return false
}

func (m *ListContentSelection) GetIssues() []*ClientIssue {
	if m != nil {
		return m.Issues
	}
	return nil
}

func (m *ListContentSelection) GetResolveAction() []*ClientResolveAction {
	if m != nil {
		return m.ResolveAction
	}
	return nil
}

func init() {
	proto.RegisterType((*Item)(nil), "Spotify.Item")
	proto.RegisterType((*ListItems)(nil), "Spotify.ListItems")
	proto.RegisterType((*ContentRange)(nil), "Spotify.ContentRange")
	proto.RegisterType((*ListContentSelection)(nil), "Spotify.ListContentSelection")
}

func init() { proto.RegisterFile("playlist4content.proto", fileDescriptor9) }

var fileDescriptor9 = []byte{
	// 435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x52, 0xdf, 0xcf, 0xd2, 0x30,
	0x14, 0xcd, 0x27, 0x8c, 0x6f, 0xbb, 0xdf, 0x20, 0x5a, 0x01, 0x1b, 0x42, 0x0c, 0x99, 0x89, 0xf1,
	0xc1, 0xf0, 0x60, 0x48, 0xd4, 0x47, 0x84, 0x17, 0x12, 0x62, 0x62, 0xd1, 0x77, 0xc7, 0xec, 0xa0,
	0x71, 0xac, 0xcb, 0xda, 0x61, 0xf8, 0xe3, 0xfc, 0xdf, 0xec, 0x8f, 0xb1, 0x1f, 0xc8, 0x5b, 0xef,
	0x39, 0xe7, 0x9e, 0xd3, 0x7b, 0x5b, 0x18, 0x67, 0x49, 0x78, 0x49, 0x98, 0x90, 0x8b, 0x88, 0xa7,
	0x92, 0xa6, 0x72, 0x9e, 0xe5, 0x5c, 0x72, 0xf4, 0xb8, 0xcb, 0xb8, 0x64, 0xf1, 0x65, 0xf2, 0xb2,
	0x12, 0x9c, 0xa8, 0x0c, 0x2d, 0x3b, 0x19, 0x55, 0x20, 0x13, 0xa2, 0xa0, 0xc2, 0xc2, 0xc1, 0x37,
	0xe8, 0x6e, 0x24, 0x3d, 0xa1, 0xe7, 0xd0, 0x29, 0x72, 0x86, 0x1f, 0x66, 0x0f, 0xef, 0x3c, 0xa2,
	0x8f, 0xe8, 0x23, 0x40, 0x28, 0x65, 0xce, 0xf6, 0x85, 0xa4, 0x02, 0x3f, 0x53, 0xc4, 0xd3, 0x87,
	0x57, 0xf3, 0x32, 0x63, 0xae, 0x9b, 0x96, 0x15, 0x4d, 0x1a, 0xd2, 0xe0, 0x27, 0x78, 0x5b, 0x95,
	0xa3, 0x15, 0x42, 0xfb, 0x66, 0x5c, 0x18, 0x5f, 0x87, 0xe8, 0x23, 0x9a, 0x82, 0x27, 0xf3, 0x22,
	0x8d, 0x42, 0x49, 0x7f, 0x19, 0x5b, 0x97, 0xd4, 0x00, 0x7a, 0x03, 0x0e, 0xd3, 0x8d, 0xb8, 0x33,
	0xeb, 0xa8, 0xc0, 0x7e, 0x2b, 0x90, 0x58, 0x2e, 0xf8, 0x04, 0xfe, 0xca, 0x8e, 0x4e, 0xc2, 0xf4,
	0x40, 0xef, 0x84, 0x8c, 0xa1, 0x97, 0xd0, 0xf4, 0x20, 0x8f, 0x26, 0xc1, 0x21, 0x65, 0x15, 0xfc,
	0xed, 0xc2, 0x50, 0x5f, 0xae, 0x6c, 0xdf, 0xd1, 0x84, 0x46, 0x92, 0xf1, 0x14, 0x05, 0xe0, 0xff,
	0x09, 0x95, 0x1f, 0x3d, 0x33, 0xa1, 0x6a, 0xe3, 0xe5, 0x92, 0x16, 0x86, 0x5e, 0x03, 0xe8, 0x7a,
	0x5b, 0x1b, 0xbb, 0xa4, 0x81, 0xa0, 0xb7, 0x30, 0xd0, 0x55, 0xbd, 0x16, 0x35, 0x84, 0xd6, 0xdc,
	0xa0, 0xd7, 0xac, 0xd5, 0x91, 0x46, 0xbf, 0x45, 0x71, 0xc2, 0xdd, 0x3a, 0xeb, 0x8a, 0xa1, 0x19,
	0x3c, 0x99, 0xda, 0xde, 0x13, 0x3b, 0x46, 0xd2, 0x84, 0xd0, 0x67, 0xf0, 0xa3, 0xc6, 0x12, 0x70,
	0xcf, 0xbc, 0xd0, 0xa8, 0x5a, 0x58, 0x73, 0x43, 0xa4, 0x25, 0x45, 0x13, 0x70, 0xb5, 0xd3, 0x9a,
	0xc5, 0x31, 0x7e, 0x34, 0xce, 0x55, 0xad, 0x2f, 0xb7, 0x0f, 0x05, 0xad, 0x16, 0xe1, 0x2a, 0xde,
	0x27, 0x2d, 0x4c, 0x6b, 0x8e, 0xac, 0xb1, 0x2c, 0xcf, 0x6a, 0x9a, 0x18, 0x5a, 0xc0, 0x48, 0x7b,
	0x7e, 0xe5, 0x52, 0xc1, 0x87, 0x4d, 0xfc, 0x23, 0xfb, 0xce, 0xd7, 0xea, 0x89, 0x31, 0x98, 0xc0,
	0xfb, 0x24, 0x7a, 0x0f, 0x2f, 0xec, 0xca, 0x05, 0x4f, 0xce, 0x74, 0x69, 0xde, 0x06, 0xfb, 0xa6,
	0xe3, 0x7f, 0x42, 0xa9, 0x7b, 0xf6, 0x33, 0xe3, 0xbe, 0xf9, 0x2d, 0xc3, 0x7a, 0xf8, 0x84, 0xa9,
	0x69, 0x37, 0x9a, 0x24, 0xa5, 0x06, 0x7d, 0x81, 0x7e, 0xde, 0xf2, 0x1d, 0x98, 0xa6, 0xe9, 0x4d,
	0x53, 0x2b, 0x82, 0xb4, 0x5b, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0xea, 0x4e, 0xf4, 0x8f, 0x7c,
	0x03, 0x00, 0x00,
}
