// Code generated by protoc-gen-go.
// source: social.proto
// DO NOT EDIT!

package Spotify

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type DecorationData struct {
	Username         *string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	FullName         *string `protobuf:"bytes,2,opt,name=full_name" json:"full_name,omitempty"`
	ImageUrl         *string `protobuf:"bytes,3,opt,name=image_url" json:"image_url,omitempty"`
	LargeImageUrl    *string `protobuf:"bytes,5,opt,name=large_image_url" json:"large_image_url,omitempty"`
	FirstName        *string `protobuf:"bytes,6,opt,name=first_name" json:"first_name,omitempty"`
	LastName         *string `protobuf:"bytes,7,opt,name=last_name" json:"last_name,omitempty"`
	FacebookUid      *string `protobuf:"bytes,8,opt,name=facebook_uid" json:"facebook_uid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DecorationData) Reset()                    { *m = DecorationData{} }
func (m *DecorationData) String() string            { return proto.CompactTextString(m) }
func (*DecorationData) ProtoMessage()               {}
func (*DecorationData) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{0} }

func (m *DecorationData) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *DecorationData) GetFullName() string {
	if m != nil && m.FullName != nil {
		return *m.FullName
	}
	return ""
}

func (m *DecorationData) GetImageUrl() string {
	if m != nil && m.ImageUrl != nil {
		return *m.ImageUrl
	}
	return ""
}

func (m *DecorationData) GetLargeImageUrl() string {
	if m != nil && m.LargeImageUrl != nil {
		return *m.LargeImageUrl
	}
	return ""
}

func (m *DecorationData) GetFirstName() string {
	if m != nil && m.FirstName != nil {
		return *m.FirstName
	}
	return ""
}

func (m *DecorationData) GetLastName() string {
	if m != nil && m.LastName != nil {
		return *m.LastName
	}
	return ""
}

func (m *DecorationData) GetFacebookUid() string {
	if m != nil && m.FacebookUid != nil {
		return *m.FacebookUid
	}
	return ""
}

func init() {
	proto.RegisterType((*DecorationData)(nil), "Spotify.DecorationData")
}

var fileDescriptor9 = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x44, 0xcb, 0x4d, 0x0a, 0xc2, 0x30,
	0x10, 0x40, 0x61, 0xaa, 0x68, 0xdb, 0xa1, 0xf8, 0x13, 0x04, 0xbb, 0x14, 0x57, 0xae, 0x3c, 0x45,
	0x6f, 0xe0, 0x01, 0xca, 0x58, 0x13, 0x19, 0x9c, 0x76, 0xca, 0x34, 0x59, 0x78, 0x19, 0xcf, 0xaa,
	0x46, 0x82, 0xdb, 0xef, 0xf1, 0xa0, 0x9a, 0xa4, 0x23, 0xe4, 0xf3, 0xa8, 0xe2, 0xc5, 0xe4, 0x97,
	0x51, 0x3c, 0xb9, 0xe7, 0xf1, 0x95, 0xc1, 0xaa, 0xb1, 0x9d, 0x28, 0x7a, 0x92, 0xa1, 0x41, 0x8f,
	0x66, 0x03, 0x45, 0x98, 0xac, 0x0e, 0xd8, 0xdb, 0x3a, 0x3b, 0x64, 0xa7, 0xd2, 0x6c, 0xa1, 0x74,
	0x81, 0xb9, 0x8d, 0x34, 0x4b, 0x44, 0x3d, 0xde, 0x6d, 0x1b, 0x94, 0xeb, 0x79, 0xa4, 0x3d, 0xac,
	0x19, 0xf5, 0x43, 0xff, 0xb0, 0x88, 0xc1, 0x00, 0x38, 0xd2, 0xc9, 0xff, 0xfe, 0x65, 0xfa, 0x19,
	0x13, 0xe5, 0x91, 0x76, 0x50, 0x39, 0xec, 0xec, 0x55, 0xe4, 0xd1, 0x06, 0xba, 0xd5, 0xc5, 0x57,
	0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0b, 0x02, 0x13, 0x66, 0xb8, 0x00, 0x00, 0x00,
}
