// Code generated by protoc-gen-go. DO NOT EDIT.
// source: playlist4ops.proto

package Spotify

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ItemAttributesPartialState_ItemAttributeKind int32

const (
	ItemAttributesPartialState_ITEM_UNKNOWN           ItemAttributesPartialState_ItemAttributeKind = 0
	ItemAttributesPartialState_ITEM_ADDED_BY          ItemAttributesPartialState_ItemAttributeKind = 1
	ItemAttributesPartialState_ITEM_TIMESTAMP         ItemAttributesPartialState_ItemAttributeKind = 2
	ItemAttributesPartialState_ITEM_MESSAGE           ItemAttributesPartialState_ItemAttributeKind = 3
	ItemAttributesPartialState_ITEM_SEEN              ItemAttributesPartialState_ItemAttributeKind = 4
	ItemAttributesPartialState_ITEM_DOWNLOAD_COUNT    ItemAttributesPartialState_ItemAttributeKind = 5
	ItemAttributesPartialState_ITEM_DOWNLOAD_FORMAT   ItemAttributesPartialState_ItemAttributeKind = 6
	ItemAttributesPartialState_ITEM_SEVENDIGITAL_ID   ItemAttributesPartialState_ItemAttributeKind = 7
	ItemAttributesPartialState_ITEM_SEVENDIGITAL_LEFT ItemAttributesPartialState_ItemAttributeKind = 8
	ItemAttributesPartialState_ITEM_SEEN_AT           ItemAttributesPartialState_ItemAttributeKind = 9
	ItemAttributesPartialState_ITEM_PUBLIC            ItemAttributesPartialState_ItemAttributeKind = 10
)

var ItemAttributesPartialState_ItemAttributeKind_name = map[int32]string{
	0:  "ITEM_UNKNOWN",
	1:  "ITEM_ADDED_BY",
	2:  "ITEM_TIMESTAMP",
	3:  "ITEM_MESSAGE",
	4:  "ITEM_SEEN",
	5:  "ITEM_DOWNLOAD_COUNT",
	6:  "ITEM_DOWNLOAD_FORMAT",
	7:  "ITEM_SEVENDIGITAL_ID",
	8:  "ITEM_SEVENDIGITAL_LEFT",
	9:  "ITEM_SEEN_AT",
	10: "ITEM_PUBLIC",
}
var ItemAttributesPartialState_ItemAttributeKind_value = map[string]int32{
	"ITEM_UNKNOWN":           0,
	"ITEM_ADDED_BY":          1,
	"ITEM_TIMESTAMP":         2,
	"ITEM_MESSAGE":           3,
	"ITEM_SEEN":              4,
	"ITEM_DOWNLOAD_COUNT":    5,
	"ITEM_DOWNLOAD_FORMAT":   6,
	"ITEM_SEVENDIGITAL_ID":   7,
	"ITEM_SEVENDIGITAL_LEFT": 8,
	"ITEM_SEEN_AT":           9,
	"ITEM_PUBLIC":            10,
}

func (x ItemAttributesPartialState_ItemAttributeKind) Enum() *ItemAttributesPartialState_ItemAttributeKind {
	p := new(ItemAttributesPartialState_ItemAttributeKind)
	*p = x
	return p
}
func (x ItemAttributesPartialState_ItemAttributeKind) String() string {
	return proto.EnumName(ItemAttributesPartialState_ItemAttributeKind_name, int32(x))
}
func (x *ItemAttributesPartialState_ItemAttributeKind) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ItemAttributesPartialState_ItemAttributeKind_value, data, "ItemAttributesPartialState_ItemAttributeKind")
	if err != nil {
		return err
	}
	*x = ItemAttributesPartialState_ItemAttributeKind(value)
	return nil
}
func (ItemAttributesPartialState_ItemAttributeKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor12, []int{3, 0}
}

type ListAttributesPartialState_ListAttributeKind int32

const (
	ListAttributesPartialState_LIST_UNKNOWN                  ListAttributesPartialState_ListAttributeKind = 0
	ListAttributesPartialState_LIST_NAME                     ListAttributesPartialState_ListAttributeKind = 1
	ListAttributesPartialState_LIST_DESCRIPTION              ListAttributesPartialState_ListAttributeKind = 2
	ListAttributesPartialState_LIST_PICTURE                  ListAttributesPartialState_ListAttributeKind = 3
	ListAttributesPartialState_LIST_COLLABORATIVE            ListAttributesPartialState_ListAttributeKind = 4
	ListAttributesPartialState_LIST_PL3_VERSION              ListAttributesPartialState_ListAttributeKind = 5
	ListAttributesPartialState_LIST_DELETED_BY_OWNER         ListAttributesPartialState_ListAttributeKind = 6
	ListAttributesPartialState_LIST_RESTRICTED_COLLABORATIVE ListAttributesPartialState_ListAttributeKind = 7
)

var ListAttributesPartialState_ListAttributeKind_name = map[int32]string{
	0: "LIST_UNKNOWN",
	1: "LIST_NAME",
	2: "LIST_DESCRIPTION",
	3: "LIST_PICTURE",
	4: "LIST_COLLABORATIVE",
	5: "LIST_PL3_VERSION",
	6: "LIST_DELETED_BY_OWNER",
	7: "LIST_RESTRICTED_COLLABORATIVE",
}
var ListAttributesPartialState_ListAttributeKind_value = map[string]int32{
	"LIST_UNKNOWN":                  0,
	"LIST_NAME":                     1,
	"LIST_DESCRIPTION":              2,
	"LIST_PICTURE":                  3,
	"LIST_COLLABORATIVE":            4,
	"LIST_PL3_VERSION":              5,
	"LIST_DELETED_BY_OWNER":         6,
	"LIST_RESTRICTED_COLLABORATIVE": 7,
}

func (x ListAttributesPartialState_ListAttributeKind) Enum() *ListAttributesPartialState_ListAttributeKind {
	p := new(ListAttributesPartialState_ListAttributeKind)
	*p = x
	return p
}
func (x ListAttributesPartialState_ListAttributeKind) String() string {
	return proto.EnumName(ListAttributesPartialState_ListAttributeKind_name, int32(x))
}
func (x *ListAttributesPartialState_ListAttributeKind) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ListAttributesPartialState_ListAttributeKind_value, data, "ListAttributesPartialState_ListAttributeKind")
	if err != nil {
		return err
	}
	*x = ListAttributesPartialState_ListAttributeKind(value)
	return nil
}
func (ListAttributesPartialState_ListAttributeKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor12, []int{4, 0}
}

type Op_Kind int32

const (
	Op_KIND_UNKNOWN           Op_Kind = 0
	Op_ADD                    Op_Kind = 2
	Op_REM                    Op_Kind = 3
	Op_MOV                    Op_Kind = 4
	Op_UPDATE_ITEM_ATTRIBUTES Op_Kind = 5
	Op_UPDATE_LIST_ATTRIBUTES Op_Kind = 6
)

var Op_Kind_name = map[int32]string{
	0: "KIND_UNKNOWN",
	2: "ADD",
	3: "REM",
	4: "MOV",
	5: "UPDATE_ITEM_ATTRIBUTES",
	6: "UPDATE_LIST_ATTRIBUTES",
}
var Op_Kind_value = map[string]int32{
	"KIND_UNKNOWN":           0,
	"ADD":                    2,
	"REM":                    3,
	"MOV":                    4,
	"UPDATE_ITEM_ATTRIBUTES": 5,
	"UPDATE_LIST_ATTRIBUTES": 6,
}

func (x Op_Kind) Enum() *Op_Kind {
	p := new(Op_Kind)
	*p = x
	return p
}
func (x Op_Kind) String() string {
	return proto.EnumName(Op_Kind_name, int32(x))
}
func (x *Op_Kind) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Op_Kind_value, data, "Op_Kind")
	if err != nil {
		return err
	}
	*x = Op_Kind(value)
	return nil
}
func (Op_Kind) EnumDescriptor() ([]byte, []int) { return fileDescriptor12, []int{7, 0} }

type Add struct {
	FromIndex        *int32        `protobuf:"varint,1,opt,name=fromIndex" json:"fromIndex,omitempty"`
	Items            []*Item       `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
	ListChecksum     *ListChecksum `protobuf:"bytes,3,opt,name=list_checksum,json=listChecksum" json:"list_checksum,omitempty"`
	AddLast          *bool         `protobuf:"varint,4,opt,name=addLast" json:"addLast,omitempty"`
	AddFirst         *bool         `protobuf:"varint,5,opt,name=addFirst" json:"addFirst,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Add) Reset()                    { *m = Add{} }
func (m *Add) String() string            { return proto.CompactTextString(m) }
func (*Add) ProtoMessage()               {}
func (*Add) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{0} }

func (m *Add) GetFromIndex() int32 {
	if m != nil && m.FromIndex != nil {
		return *m.FromIndex
	}
	return 0
}

func (m *Add) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Add) GetListChecksum() *ListChecksum {
	if m != nil {
		return m.ListChecksum
	}
	return nil
}

func (m *Add) GetAddLast() bool {
	if m != nil && m.AddLast != nil {
		return *m.AddLast
	}
	return false
}

func (m *Add) GetAddFirst() bool {
	if m != nil && m.AddFirst != nil {
		return *m.AddFirst
	}
	return false
}

type Rem struct {
	FromIndex        *int32        `protobuf:"varint,1,opt,name=fromIndex" json:"fromIndex,omitempty"`
	Length           *int32        `protobuf:"varint,2,opt,name=length" json:"length,omitempty"`
	Items            []*Item       `protobuf:"bytes,3,rep,name=items" json:"items,omitempty"`
	ListChecksum     *ListChecksum `protobuf:"bytes,4,opt,name=list_checksum,json=listChecksum" json:"list_checksum,omitempty"`
	ItemsChecksum    *ListChecksum `protobuf:"bytes,5,opt,name=items_checksum,json=itemsChecksum" json:"items_checksum,omitempty"`
	UrisChecksum     *ListChecksum `protobuf:"bytes,6,opt,name=uris_checksum,json=urisChecksum" json:"uris_checksum,omitempty"`
	ItemsAsKey       *bool         `protobuf:"varint,7,opt,name=itemsAsKey" json:"itemsAsKey,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Rem) Reset()                    { *m = Rem{} }
func (m *Rem) String() string            { return proto.CompactTextString(m) }
func (*Rem) ProtoMessage()               {}
func (*Rem) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{1} }

func (m *Rem) GetFromIndex() int32 {
	if m != nil && m.FromIndex != nil {
		return *m.FromIndex
	}
	return 0
}

func (m *Rem) GetLength() int32 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *Rem) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Rem) GetListChecksum() *ListChecksum {
	if m != nil {
		return m.ListChecksum
	}
	return nil
}

func (m *Rem) GetItemsChecksum() *ListChecksum {
	if m != nil {
		return m.ItemsChecksum
	}
	return nil
}

func (m *Rem) GetUrisChecksum() *ListChecksum {
	if m != nil {
		return m.UrisChecksum
	}
	return nil
}

func (m *Rem) GetItemsAsKey() bool {
	if m != nil && m.ItemsAsKey != nil {
		return *m.ItemsAsKey
	}
	return false
}

type Mov struct {
	FromIndex        *int32        `protobuf:"varint,1,opt,name=fromIndex" json:"fromIndex,omitempty"`
	Length           *int32        `protobuf:"varint,2,opt,name=length" json:"length,omitempty"`
	ToIndex          *int32        `protobuf:"varint,3,opt,name=toIndex" json:"toIndex,omitempty"`
	ListChecksum     *ListChecksum `protobuf:"bytes,4,opt,name=list_checksum,json=listChecksum" json:"list_checksum,omitempty"`
	ItemsChecksum    *ListChecksum `protobuf:"bytes,5,opt,name=items_checksum,json=itemsChecksum" json:"items_checksum,omitempty"`
	UrisChecksum     *ListChecksum `protobuf:"bytes,6,opt,name=uris_checksum,json=urisChecksum" json:"uris_checksum,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Mov) Reset()                    { *m = Mov{} }
func (m *Mov) String() string            { return proto.CompactTextString(m) }
func (*Mov) ProtoMessage()               {}
func (*Mov) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{2} }

func (m *Mov) GetFromIndex() int32 {
	if m != nil && m.FromIndex != nil {
		return *m.FromIndex
	}
	return 0
}

func (m *Mov) GetLength() int32 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *Mov) GetToIndex() int32 {
	if m != nil && m.ToIndex != nil {
		return *m.ToIndex
	}
	return 0
}

func (m *Mov) GetListChecksum() *ListChecksum {
	if m != nil {
		return m.ListChecksum
	}
	return nil
}

func (m *Mov) GetItemsChecksum() *ListChecksum {
	if m != nil {
		return m.ItemsChecksum
	}
	return nil
}

func (m *Mov) GetUrisChecksum() *ListChecksum {
	if m != nil {
		return m.UrisChecksum
	}
	return nil
}

type ItemAttributesPartialState struct {
	Values           *ItemAttributes                                `protobuf:"bytes,1,opt,name=values" json:"values,omitempty"`
	NoValue          []ItemAttributesPartialState_ItemAttributeKind `protobuf:"varint,2,rep,name=no_value,json=noValue,enum=Spotify.ItemAttributesPartialState_ItemAttributeKind" json:"no_value,omitempty"`
	XXX_unrecognized []byte                                         `json:"-"`
}

func (m *ItemAttributesPartialState) Reset()                    { *m = ItemAttributesPartialState{} }
func (m *ItemAttributesPartialState) String() string            { return proto.CompactTextString(m) }
func (*ItemAttributesPartialState) ProtoMessage()               {}
func (*ItemAttributesPartialState) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{3} }

func (m *ItemAttributesPartialState) GetValues() *ItemAttributes {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *ItemAttributesPartialState) GetNoValue() []ItemAttributesPartialState_ItemAttributeKind {
	if m != nil {
		return m.NoValue
	}
	return nil
}

type ListAttributesPartialState struct {
	Values           *ListAttributes                                `protobuf:"bytes,1,opt,name=values" json:"values,omitempty"`
	NoValue          []ListAttributesPartialState_ListAttributeKind `protobuf:"varint,2,rep,name=no_value,json=noValue,enum=Spotify.ListAttributesPartialState_ListAttributeKind" json:"no_value,omitempty"`
	XXX_unrecognized []byte                                         `json:"-"`
}

func (m *ListAttributesPartialState) Reset()                    { *m = ListAttributesPartialState{} }
func (m *ListAttributesPartialState) String() string            { return proto.CompactTextString(m) }
func (*ListAttributesPartialState) ProtoMessage()               {}
func (*ListAttributesPartialState) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{4} }

func (m *ListAttributesPartialState) GetValues() *ListAttributes {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *ListAttributesPartialState) GetNoValue() []ListAttributesPartialState_ListAttributeKind {
	if m != nil {
		return m.NoValue
	}
	return nil
}

type UpdateItemAttributes struct {
	Index                 *int32                      `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	NewAttributes         *ItemAttributesPartialState `protobuf:"bytes,2,opt,name=new_attributes,json=newAttributes" json:"new_attributes,omitempty"`
	OldAttributes         *ItemAttributesPartialState `protobuf:"bytes,3,opt,name=old_attributes,json=oldAttributes" json:"old_attributes,omitempty"`
	ListChecksum          *ListChecksum               `protobuf:"bytes,4,opt,name=list_checksum,json=listChecksum" json:"list_checksum,omitempty"`
	OldAttributesChecksum *ListChecksum               `protobuf:"bytes,5,opt,name=old_attributes_checksum,json=oldAttributesChecksum" json:"old_attributes_checksum,omitempty"`
	XXX_unrecognized      []byte                      `json:"-"`
}

func (m *UpdateItemAttributes) Reset()                    { *m = UpdateItemAttributes{} }
func (m *UpdateItemAttributes) String() string            { return proto.CompactTextString(m) }
func (*UpdateItemAttributes) ProtoMessage()               {}
func (*UpdateItemAttributes) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{5} }

func (m *UpdateItemAttributes) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *UpdateItemAttributes) GetNewAttributes() *ItemAttributesPartialState {
	if m != nil {
		return m.NewAttributes
	}
	return nil
}

func (m *UpdateItemAttributes) GetOldAttributes() *ItemAttributesPartialState {
	if m != nil {
		return m.OldAttributes
	}
	return nil
}

func (m *UpdateItemAttributes) GetListChecksum() *ListChecksum {
	if m != nil {
		return m.ListChecksum
	}
	return nil
}

func (m *UpdateItemAttributes) GetOldAttributesChecksum() *ListChecksum {
	if m != nil {
		return m.OldAttributesChecksum
	}
	return nil
}

type UpdateListAttributes struct {
	NewAttributes         *ListAttributesPartialState `protobuf:"bytes,1,opt,name=new_attributes,json=newAttributes" json:"new_attributes,omitempty"`
	OldAttributes         *ListAttributesPartialState `protobuf:"bytes,2,opt,name=old_attributes,json=oldAttributes" json:"old_attributes,omitempty"`
	ListChecksum          *ListChecksum               `protobuf:"bytes,3,opt,name=list_checksum,json=listChecksum" json:"list_checksum,omitempty"`
	OldAttributesChecksum *ListChecksum               `protobuf:"bytes,4,opt,name=old_attributes_checksum,json=oldAttributesChecksum" json:"old_attributes_checksum,omitempty"`
	XXX_unrecognized      []byte                      `json:"-"`
}

func (m *UpdateListAttributes) Reset()                    { *m = UpdateListAttributes{} }
func (m *UpdateListAttributes) String() string            { return proto.CompactTextString(m) }
func (*UpdateListAttributes) ProtoMessage()               {}
func (*UpdateListAttributes) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{6} }

func (m *UpdateListAttributes) GetNewAttributes() *ListAttributesPartialState {
	if m != nil {
		return m.NewAttributes
	}
	return nil
}

func (m *UpdateListAttributes) GetOldAttributes() *ListAttributesPartialState {
	if m != nil {
		return m.OldAttributes
	}
	return nil
}

func (m *UpdateListAttributes) GetListChecksum() *ListChecksum {
	if m != nil {
		return m.ListChecksum
	}
	return nil
}

func (m *UpdateListAttributes) GetOldAttributesChecksum() *ListChecksum {
	if m != nil {
		return m.OldAttributesChecksum
	}
	return nil
}

type Op struct {
	Kind                 *Op_Kind              `protobuf:"varint,1,opt,name=kind,enum=Spotify.Op_Kind" json:"kind,omitempty"`
	Add                  *Add                  `protobuf:"bytes,2,opt,name=add" json:"add,omitempty"`
	Rem                  *Rem                  `protobuf:"bytes,3,opt,name=rem" json:"rem,omitempty"`
	Mov                  *Mov                  `protobuf:"bytes,4,opt,name=mov" json:"mov,omitempty"`
	UpdateItemAttributes *UpdateItemAttributes `protobuf:"bytes,5,opt,name=update_item_attributes,json=updateItemAttributes" json:"update_item_attributes,omitempty"`
	UpdateListAttributes *UpdateListAttributes `protobuf:"bytes,6,opt,name=update_list_attributes,json=updateListAttributes" json:"update_list_attributes,omitempty"`
	XXX_unrecognized     []byte                `json:"-"`
}

func (m *Op) Reset()                    { *m = Op{} }
func (m *Op) String() string            { return proto.CompactTextString(m) }
func (*Op) ProtoMessage()               {}
func (*Op) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{7} }

func (m *Op) GetKind() Op_Kind {
	if m != nil && m.Kind != nil {
		return *m.Kind
	}
	return Op_KIND_UNKNOWN
}

func (m *Op) GetAdd() *Add {
	if m != nil {
		return m.Add
	}
	return nil
}

func (m *Op) GetRem() *Rem {
	if m != nil {
		return m.Rem
	}
	return nil
}

func (m *Op) GetMov() *Mov {
	if m != nil {
		return m.Mov
	}
	return nil
}

func (m *Op) GetUpdateItemAttributes() *UpdateItemAttributes {
	if m != nil {
		return m.UpdateItemAttributes
	}
	return nil
}

func (m *Op) GetUpdateListAttributes() *UpdateListAttributes {
	if m != nil {
		return m.UpdateListAttributes
	}
	return nil
}

type OpList struct {
	Ops              []*Op  `protobuf:"bytes,1,rep,name=ops" json:"ops,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *OpList) Reset()                    { *m = OpList{} }
func (m *OpList) String() string            { return proto.CompactTextString(m) }
func (*OpList) ProtoMessage()               {}
func (*OpList) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{8} }

func (m *OpList) GetOps() []*Op {
	if m != nil {
		return m.Ops
	}
	return nil
}

func init() {
	proto.RegisterType((*Add)(nil), "Spotify.Add")
	proto.RegisterType((*Rem)(nil), "Spotify.Rem")
	proto.RegisterType((*Mov)(nil), "Spotify.Mov")
	proto.RegisterType((*ItemAttributesPartialState)(nil), "Spotify.ItemAttributesPartialState")
	proto.RegisterType((*ListAttributesPartialState)(nil), "Spotify.ListAttributesPartialState")
	proto.RegisterType((*UpdateItemAttributes)(nil), "Spotify.UpdateItemAttributes")
	proto.RegisterType((*UpdateListAttributes)(nil), "Spotify.UpdateListAttributes")
	proto.RegisterType((*Op)(nil), "Spotify.Op")
	proto.RegisterType((*OpList)(nil), "Spotify.OpList")
	proto.RegisterEnum("Spotify.ItemAttributesPartialState_ItemAttributeKind", ItemAttributesPartialState_ItemAttributeKind_name, ItemAttributesPartialState_ItemAttributeKind_value)
	proto.RegisterEnum("Spotify.ListAttributesPartialState_ListAttributeKind", ListAttributesPartialState_ListAttributeKind_name, ListAttributesPartialState_ListAttributeKind_value)
	proto.RegisterEnum("Spotify.Op_Kind", Op_Kind_name, Op_Kind_value)
}

func init() { proto.RegisterFile("playlist4ops.proto", fileDescriptor12) }

var fileDescriptor12 = []byte{
	// 952 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0xcd, 0x72, 0xe3, 0x44,
	0x10, 0x46, 0x92, 0x7f, 0x92, 0xf6, 0xda, 0x4c, 0x66, 0x1d, 0x47, 0xb8, 0xc8, 0x56, 0xf0, 0x52,
	0x45, 0x4e, 0xa1, 0xca, 0xc0, 0x65, 0x8b, 0x8b, 0x62, 0x4d, 0xb6, 0xb4, 0xd1, 0x8f, 0x6b, 0x24,
	0x3b, 0xc5, 0x49, 0x25, 0x22, 0x2d, 0xab, 0x8a, 0x2d, 0xa9, 0xac, 0x71, 0x96, 0x3c, 0x03, 0x8f,
	0xc0, 0x89, 0x97, 0xa0, 0x0a, 0x9e, 0x80, 0x1b, 0xef, 0xc1, 0x1b, 0x70, 0xa3, 0x66, 0xec, 0xc8,
	0xd2, 0x26, 0xd9, 0x24, 0x0b, 0x17, 0x6e, 0xee, 0xfe, 0xa6, 0xbf, 0x9e, 0xfe, 0xba, 0xa7, 0x65,
	0xc0, 0xd9, 0x2c, 0xb8, 0x9a, 0xc5, 0x39, 0xfb, 0x3a, 0xcd, 0xf2, 0xa3, 0x6c, 0x91, 0xb2, 0x14,
	0x37, 0xdd, 0x2c, 0x65, 0xf1, 0xeb, 0xab, 0xfe, 0xd3, 0x02, 0x9c, 0x47, 0x2c, 0x58, 0xa1, 0xfd,
	0x5e, 0xe1, 0x3c, 0x4f, 0x13, 0x16, 0x25, 0x6c, 0xe5, 0x1f, 0xfc, 0x2e, 0x81, 0xa2, 0x85, 0x21,
	0xfe, 0x14, 0xb6, 0x5f, 0x2f, 0xd2, 0xb9, 0x91, 0x84, 0xd1, 0x8f, 0xaa, 0x74, 0x20, 0x1d, 0xd6,
	0xe9, 0xc6, 0x81, 0x9f, 0x43, 0x3d, 0x66, 0xd1, 0x3c, 0x57, 0xe5, 0x03, 0xe5, 0xb0, 0x35, 0x6c,
	0x1f, 0xad, 0x73, 0x1d, 0x19, 0x2c, 0x9a, 0xd3, 0x15, 0x86, 0x5f, 0x40, 0x9b, 0x27, 0xf0, 0xcf,
	0xdf, 0x44, 0xe7, 0x17, 0xf9, 0x72, 0xae, 0x2a, 0x07, 0xd2, 0x61, 0x6b, 0xb8, 0x5b, 0x1c, 0x36,
	0xe3, 0x9c, 0x8d, 0xd6, 0x20, 0x7d, 0x32, 0x2b, 0x59, 0x58, 0x85, 0x66, 0x10, 0x86, 0x66, 0x90,
	0x33, 0xb5, 0x76, 0x20, 0x1d, 0x6e, 0xd1, 0x6b, 0x13, 0xf7, 0x61, 0x2b, 0x08, 0xc3, 0x93, 0x78,
	0x91, 0x33, 0xb5, 0x2e, 0xa0, 0xc2, 0x1e, 0xfc, 0x2a, 0x83, 0x42, 0xa3, 0xf9, 0x3d, 0x97, 0xef,
	0x41, 0x63, 0x16, 0x25, 0x3f, 0xb0, 0x37, 0xaa, 0x2c, 0xa0, 0xb5, 0xb5, 0x29, 0x4a, 0x79, 0x4c,
	0x51, 0xb5, 0x87, 0x17, 0xf5, 0x2d, 0x74, 0x04, 0xc9, 0x26, 0xb8, 0xfe, 0xbe, 0xe0, 0xb6, 0x38,
	0x5c, 0x44, 0xbf, 0x80, 0xf6, 0x72, 0x11, 0x97, 0x82, 0x1b, 0xef, 0xcd, 0xcc, 0xcf, 0x16, 0xb1,
	0xcf, 0x00, 0x04, 0x99, 0x96, 0x9f, 0x46, 0x57, 0x6a, 0x53, 0xc8, 0x56, 0xf2, 0x0c, 0x7e, 0x92,
	0x41, 0xb1, 0xd2, 0xcb, 0x0f, 0x14, 0x4e, 0x85, 0x26, 0x4b, 0x57, 0x31, 0x8a, 0x00, 0xae, 0xcd,
	0xff, 0xa7, 0x5a, 0x83, 0x9f, 0x15, 0xe8, 0xf3, 0x9e, 0x6b, 0x8c, 0x2d, 0xe2, 0xef, 0x97, 0x2c,
	0xca, 0xc7, 0xc1, 0x82, 0xc5, 0xc1, 0xcc, 0x65, 0x01, 0x8b, 0xf0, 0x97, 0xd0, 0xb8, 0x0c, 0x66,
	0xcb, 0x28, 0x17, 0x0a, 0xb5, 0x86, 0x7b, 0x95, 0x41, 0xd9, 0x04, 0xd1, 0xf5, 0x31, 0x3c, 0x86,
	0xad, 0x24, 0xf5, 0x85, 0x21, 0x1e, 0x4c, 0x67, 0xf8, 0xcd, 0x1d, 0x21, 0xe5, 0x3c, 0x55, 0xe8,
	0x34, 0x4e, 0x42, 0xda, 0x4c, 0xd2, 0x29, 0x67, 0x19, 0xfc, 0x2d, 0xc1, 0xce, 0x0d, 0x18, 0x23,
	0x78, 0x62, 0x78, 0xc4, 0xf2, 0x27, 0xf6, 0xa9, 0xed, 0x9c, 0xd9, 0xe8, 0x23, 0xbc, 0x03, 0x6d,
	0xe1, 0xd1, 0x74, 0x9d, 0xe8, 0xfe, 0xf1, 0x77, 0x48, 0xc2, 0x18, 0x3a, 0xc2, 0xe5, 0x19, 0x16,
	0x71, 0x3d, 0xcd, 0x1a, 0x23, 0xb9, 0x08, 0xb4, 0x88, 0xeb, 0x6a, 0x2f, 0x09, 0x52, 0x70, 0x1b,
	0xb6, 0x85, 0xc7, 0x25, 0xc4, 0x46, 0x35, 0xbc, 0x07, 0x4f, 0x85, 0xa9, 0x3b, 0x67, 0xb6, 0xe9,
	0x68, 0xba, 0x3f, 0x72, 0x26, 0xb6, 0x87, 0xea, 0x58, 0x85, 0x6e, 0x15, 0x38, 0x71, 0xa8, 0xa5,
	0x79, 0xa8, 0x51, 0x20, 0x2e, 0x99, 0x12, 0x5b, 0x37, 0x5e, 0x1a, 0x9e, 0x66, 0xfa, 0x86, 0x8e,
	0x9a, 0xb8, 0x0f, 0xbd, 0x9b, 0x88, 0x49, 0x4e, 0x3c, 0xb4, 0x55, 0xdc, 0x84, 0xe7, 0xf5, 0x35,
	0x0f, 0x6d, 0xe3, 0x8f, 0xa1, 0x25, 0x3c, 0xe3, 0xc9, 0xb1, 0x69, 0x8c, 0x10, 0x0c, 0xfe, 0x92,
	0xa1, 0xcf, 0x9b, 0xf7, 0xe8, 0xee, 0x54, 0x83, 0x1e, 0xd4, 0x9d, 0xbb, 0xf3, 0x54, 0xa1, 0x6a,
	0x77, 0xfe, 0x90, 0x60, 0xe7, 0x06, 0xcc, 0x4b, 0x33, 0x0d, 0xd7, 0x2b, 0x75, 0xa7, 0x0d, 0xdb,
	0xc2, 0x63, 0x6b, 0x16, 0x41, 0x12, 0xee, 0x02, 0x12, 0xa6, 0x4e, 0xdc, 0x11, 0x35, 0xc6, 0x9e,
	0xe1, 0xd8, 0xab, 0xde, 0x08, 0xef, 0xd8, 0x18, 0x79, 0x13, 0xca, 0x7b, 0xd3, 0x03, 0x2c, 0x3c,
	0x23, 0xc7, 0x34, 0xb5, 0x63, 0x87, 0x6a, 0x9e, 0x31, 0x25, 0xa8, 0x56, 0xc4, 0x8f, 0xcd, 0xaf,
	0xfc, 0x29, 0xa1, 0x2e, 0x8f, 0xaf, 0xe3, 0x4f, 0x60, 0x77, 0xcd, 0x6a, 0x12, 0x4f, 0x0c, 0x81,
	0xef, 0x9c, 0xd9, 0x84, 0xa2, 0x06, 0xfe, 0x0c, 0xf6, 0x05, 0x44, 0x89, 0xeb, 0x51, 0x63, 0xc4,
	0xd1, 0x2a, 0x67, 0x73, 0xf0, 0xa7, 0x0c, 0xdd, 0x49, 0x16, 0x06, 0x2c, 0xaa, 0x0e, 0x2a, 0xee,
	0x42, 0x3d, 0x2e, 0x6d, 0x89, 0x95, 0x81, 0x5f, 0x41, 0x27, 0x89, 0xde, 0xfa, 0x41, 0x71, 0x4e,
	0x6c, 0x8a, 0xd6, 0xf0, 0xf9, 0x03, 0xe6, 0x9d, 0xb6, 0x93, 0xe8, 0x6d, 0x29, 0xc3, 0x2b, 0xe8,
	0xa4, 0xb3, 0xb0, 0xcc, 0xa5, 0x3c, 0x82, 0x2b, 0x9d, 0x85, 0x25, 0xae, 0x7f, 0xb3, 0x87, 0x2c,
	0xd8, 0xab, 0xde, 0xe3, 0x81, 0x0b, 0x69, 0xb7, 0x72, 0x85, 0x62, 0xb9, 0xfc, 0x56, 0x28, 0x5a,
	0x1d, 0xae, 0x5b, 0xb4, 0x93, 0xde, 0xa9, 0xf7, 0xee, 0x69, 0xbc, 0x5f, 0x3b, 0xf9, 0x11, 0x5c,
	0xf7, 0x68, 0xa7, 0xfc, 0x27, 0xda, 0xd5, 0x3e, 0x40, 0xbb, 0x5f, 0x14, 0x90, 0x9d, 0x0c, 0x7f,
	0x0e, 0xb5, 0x8b, 0x38, 0x09, 0x85, 0x3e, 0x9d, 0x21, 0x2a, 0x28, 0x9c, 0xec, 0x48, 0x3c, 0x44,
	0x81, 0xe2, 0x67, 0xa0, 0x04, 0x61, 0xb8, 0x2e, 0xfc, 0x49, 0x71, 0x48, 0x0b, 0x43, 0xca, 0x01,
	0x8e, 0x2f, 0xa2, 0xeb, 0x6a, 0x36, 0x38, 0x8d, 0xe6, 0x94, 0x03, 0x1c, 0x9f, 0xa7, 0x97, 0xeb,
	0x7b, 0x6e, 0x70, 0x2b, 0xbd, 0xa4, 0x1c, 0xc0, 0x2e, 0xf4, 0x96, 0xa2, 0x8f, 0x3e, 0xff, 0xf2,
	0x94, 0xb5, 0x5e, 0x8d, 0xc5, 0x7e, 0x11, 0x72, 0xdb, 0x03, 0xa2, 0xdd, 0xe5, 0x6d, 0xcf, 0x6a,
	0x43, 0x2a, 0x34, 0x2f, 0x91, 0x36, 0x6e, 0x25, 0x7d, 0x67, 0xa7, 0xad, 0x49, 0xab, 0xde, 0xc1,
	0x05, 0xd4, 0xae, 0x37, 0xd0, 0xa9, 0x61, 0xeb, 0xa5, 0x0d, 0xd4, 0x04, 0x45, 0xd3, 0x75, 0x24,
	0xf3, 0x1f, 0x94, 0x58, 0x48, 0xe1, 0x3f, 0x2c, 0x67, 0x8a, 0x6a, 0x7c, 0x4b, 0x4f, 0xc6, 0xba,
	0xe6, 0x11, 0x7f, 0xf5, 0x05, 0xf1, 0x3c, 0x6a, 0x1c, 0x4f, 0x3c, 0xe2, 0xa2, 0x7a, 0x09, 0x13,
	0xfb, 0xa3, 0x84, 0x35, 0x06, 0x5f, 0x40, 0xc3, 0xc9, 0xf8, 0x05, 0xf0, 0x3e, 0x28, 0x69, 0xc6,
	0xa7, 0x98, 0xff, 0x9b, 0x6a, 0x95, 0xba, 0x44, 0xb9, 0xff, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x50, 0x86, 0x18, 0xc9, 0xb4, 0x0a, 0x00, 0x00,
}
